[package]
name = "dtiku-backend"
version = "0.0.1"
edition = "2021"
publish = ["crates-io"]

[dependencies]
spring = "0.2"
spring-web = "0.2"
spring-stream = "0.2"
spring-job = "0.2"
spring-sea-orm = "0.2"
tokio = { workspace = true, features = ["full"] }
dtiku-paper = { path = "../dtiku-paper", version = "0.0.1" }
