//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::TopicType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "issue")]
pub struct Model {
    // --- 小字段放前面 ---
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub topic: TopicType,
    pub pin: bool,
    pub collect: bool,
    pub paid: bool,

    // --- 大字段放后面，连续排布 ---
    pub created: DateTime,
    pub modified: DateTime,

    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub markdown: String,
    #[sea_orm(column_type = "Text")]
    pub html: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
