//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "topic_type")]
#[serde(rename_all = "snake_case")]
pub enum TopicType {
    #[sea_orm(string_value = "linxuan")]
    Linxuan,
    #[sea_orm(string_value = "mianshi")]
    Mianshi,
    #[sea_orm(string_value = "share")]
    Share,
    #[sea_orm(string_value = "shenhe")]
    Shenhe,
    #[sea_orm(string_value = "shenlun")]
    Shenlun,
    #[sea_orm(string_value = "sydw")]
    Sydw,
    #[sea_orm(string_value = "work")]
    Work,
    #[sea_orm(string_value = "xingce")]
    Xingce,
}
