services:
  postgres:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    volumes:
      - ./ddl:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432