services:
  postgres:
    image: holmofy/postgresql:latest
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ./docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432
  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379