services:
  postgres:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    volumes:
      - ./sql/01_paper.sql:/docker-entrypoint-initdb.d/01_paper.sql
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432