[package]
name = "dtiku-macros"
version = "0.0.1"
edition = "2021"
publish = ["crates-io"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
darling = "0.20"