//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::IdiomType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "idiom_ref")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub idiom_id: i32,
    pub question_id: i32,
    pub paper_id: i32,
    pub sort: i16,
    pub label_id: i32,
    pub exam_id: i16,
    pub paper_type: i16,
    pub ty: IdiomType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
