//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "idiom_type")]
#[serde(rename_all = "snake_case")]
pub enum IdiomType {
    #[sea_orm(string_value = "idiom")]
    Idiom,
    #[sea_orm(string_value = "word")]
    Word,
}
