[package]
name = "dtiku-bbs"
version = "0.0.1"
edition = "2021"

[dependencies]
spring.workspace = true
sea-orm = { workspace = true, features = ["sqlx-postgres"] }
serde.workspace = true
strum = { workspace = true, features = ["derive"] }
