[package]
name = "dtiku-stats"
version = "0.0.1"
edition = "2021"

[dependencies]
dtiku-paper = { path = "../dtiku-paper", version = "0.0.1" }
strum = { workspace = true, features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }