#:schema https://spring-rs.github.io/config-schema.json
[web]
port = 18080
graceful = true
connect_info = true

[web.middlewares]
static = { enable = true, uri = "/static", path = "static", precompressed = true }
# 因为和opentelemetry冲突所以写到代码里
logger = { enable = false, level = "${WEB_LOG_LEVEL:info}", override_filter = "${WEB_LOG_LEVEL_FILTER:info}" }

[sea-orm]
uri = "${DATABASE_URL:postgres://postgres:12345@localhost:5432/empty_tiku}"

[sea-orm-web]
one_indexed = true

[redis]
uri = "${REDIS_URL:redis://localhost}"

[opentelemetry]
enable = false

[site]
navbar_brand = "公考加油站"
site_title = "公考加油站"
show_ads = false
ads_script = ""
show_comments = true
show_visitors = true
show_solution = true
show_vendor = false
use_cdn_asset = false
cdn_assets = ""
alert_message_key = ""
global_alert_message = ""
analytics_script = ""
global_style = ""
global_head_files = ""
iconfont_js_url = "//at.alicdn.com/t/c/font_4936584_v34jg0cgwt.js"
block_ip_pv_threshold = 1000
block_user_agents = ""
seo_user_agents = ""
ip_blacklist = ""

[grpc-client]
embedding_url = "${EMBEDDING_GRPC_URL:http://localhost:18000}"
artalk_url = "${ARTALK_GRPC_URL:http://localhost:18090}"

[web-dav-client]
username = "${WEB_DAV_USERNAME:xxx}"
password = "${WEB_DAV_PASSWORD:xxx}"

[opendal]
scheme = "webdav"
options = { endpoint = "${WEB_DAV_HOST:https://alist.dtiku.cn/dav}", username = "${WEB_DAV_USERNAME:xxx}", password = "${WEB_DAV_PASSWORD:xxx}" }
layers = ["Tracing"]

[pay]
## https://openhome.alipay.com/develop/sandbox/app
wechat_pay_enable = false
alipay_enable = true
alipay_api_url = "${ALIPAY_API_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}"
alipay_app_id = "${ALIPAY_APP_ID:2021000149633962}" ## 沙箱应用 // https://open.alipay.com/develop/sandbox/app
alipay_root_cert_sn = "${ALIPAY_ROOT_CERT_SN:687b59193f3f462dd5336e5abf83c5d8_02941eef3187dddf3d3b83462e1dfcf6}"
alipay_public_key = "${ALIPAY_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhwTnltzqSlQUJj+KaaU1GGdkNI4z+g0BoQhB3iHT/Bg3u6dOvT1gbwhxYNfusXwCy+e9Bl5ANkf5ei95mz+O0NOK0zr9jK6IQ58mYwb3+lsRoSSEXHiffvrBqc/AyqA9CDytv58eB+J9gRhu9vIUeVh3KFTwrjM14VzjyhwNR0VY/y3qQBwe3eyNxKCiXwJwGd66ZZQ/9NMvLdJ1m1uHzJ2Qz8ac5ohhMlo0SYvdp/aoJVSd5Es0AKGdQs4prhnkJU52CrR7mI506123j4Cpp/eiKS2GD/xixLhIZspSUe2h5Y7Ue6CsIXpK0cNdmB2UkiAFUtFDtzQwmL9Qs9fSKQIDAQAB}"
alipay_app_cert_sn = "${ALIPAY_APP_CERT_SN:f4347077035aa27f572136d302b14b53}"
alipay_app_private_key = "${ALIPAY_APP_PRIVATE_KEY:MIIEpAIBAAKCAQEAlAr7sCWIqhUHMIZ44k8VPuIdCbDXK1v8YOTcMPykbNWD9SgMOHPICW1h9TolKcNu4jFUfVoKPBrDskmFWU0v9jJvyBF5ijrIxiSFPGdZBE8SvvhfBSGV8YWpWdOxdBrSgj+t3jF4YMqS+PWxE0W8I3mO2Q/zOf5obzF57ChNvC+uzMUTgKrCK8QFvW/wy7gVk7RFmPBHflcFIOIMRy0At6zX12LFW2jYdwyUi/aYvBa35GMGWJ1aK1QYHYpWgf/8zFk8DFAkMZv+wD9rBkSDUXcyfQFcyP+mCh5q2gbqJZpGMnbhMPW9NtaN3KOadVqElLgas/2PzuaApALEWfXGYwIDAQABAoIBAQCRgZILeXivoudkHGdoF86L9fYQdk2mAk02dvqs80Qw7FM8fFY2jiYIjgf/3Vx1he7QRygB5KO2m5/I9lYohaMkWkJf5D0PTePUTETgL7vgbk/Af6H1CyOzNWpULat2sH5DIo+jmf/1MmXuaJ3YkWvveiSa2AB5+cFvuLNbF+n/kWRlqxcJxsECX0IpXors+PjS6gr5l/+VkgYiDMEzdJhSIZJqLJ1u1/uusFPBRKef7gGNFg4lMlDEzldg86MfXbUUJGESTzFjBeWlI+GpHORBRiGFEv+ibOIqiWKbbHksYAnJ8DkKDBSwBWtb3upTWFgOX0qz6HI+nKsnvQm0C9QxAoGBAN1diJ11Spr0rB0CCZKNYkuDUvLtMDNXidiV3R+/8wM9KyLNqzxfYshKp4Zaypjh9nXKjDoPFtwhPdvAljxgqOwt7KL5SE3kGe6cKpWlDsp8MmIAggIGeteAX5Co2dmRf40rDfsvUfQyVDvevXk9+NxVkO+rDLkZDBmw6IQl2BZPAoGBAKs0oBgCXuTpXv/FwQtdlNaZbyNUoUX1h538I9Kz06s/YKmqH4kxeu/iM+A0BA3jDcGHPKmB1tg+UAVw8rf+OE9hpsjh4CKZsKu/CG44FOmrI8juLRFnl8cXsW45KPoQlRMcPjHd2c8O4ayHapF5Hx0zBKKbz2P13g0tPNpq7F2tAoGAS+822tSOSANgOv8k63nGWyLsRFqqqyH/LiWSWb7NjLHh5yln8OjDiPNa7hKc5r60fYmCerQMYmygvI4euw1pRMMoJmuequFxJ9G4Jecd4MWjvsxvzGQOpXfq0EOrnx9zAqjfPefok/zjujnZAwsIIATWF/C0B5aY+QMfb51Pt68CgYEAp4cCVRwUwUh/FibrBHUZDHjtYJQSj4N3picw4p/msv58VulKnJPXaV5eRrh/cxtHvaTYvkF3+vfWk8x3JYXUkhDLBGzKRvE/CIAQ/tFP3WsCxD4TyaElysKrc2DpcPDC/wU28tLUrCEywQFtTVZJFOh0U63FXVocY6ZtkojoK60CgYBhSWe2XsDs1Wzx+jFYGVpMxQ6bVsT6/VhZXS1dD0VZ5f+EZ3ExSxcSGNHxiVSbict5nGDEE93JrfTlLSVPEhXzK8qvzkIywHMfwK/BDMdoM9gBZaA4w7hOWXwUEj1gpbolsOmicbSURvPNzH8QLf3wDAozOD9k+crhwEr5HCoUdw==}"
alipay_app_public_key = "${ALIPAY_APP_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkT0nqFBP7j3bsHacp+y2d5G6ShSnwXH4rfrWCOdGT9h2iRTrOvzdwWWAhSpBeGOmo/ePakbpe5wpgbHBdhM8k7xDKkdK3d5KeOrP6ugOUkIpCyJX17fgOI1WSTEHjjpQorHRTUXeqaAqc9wJa6+P4K5Yb/XdNFATXq7SY/hs+r/dPZbWRHvLXXcR0SkxvJrlvx7YSBayuLEjJ4ezGDiiyyPlCutHqyS3HXWMkVCCMflqqVkVqiVkd7GGCAFiCaAul/Uhxkn/1qYjnLwnfmBTIP9VdaDjRSFJJcvdG4HygXeT0qrGyDWISD/sOwjqaYwncsyBNQyicRKM3PjNpMFt7wIDAQAB}"
yishoumi_appid = "${YISHOUMI_APPID:YSM8d9c705a}"
yishoumi_secret = "${YISHOUMI_SECRET}"
yishoumi_notify_url = "${YISHOUMI_NOTIFY_URL:https://gwy.dtiku.cn/pay/notify}"
yishoumi_nopay_url = "${YISHOUMI_NOPAY_URL:https://gwy.dtiku.cn/pay/nopay}"
yishoumi_callback_url = "${YISHOUMI_CALLBACK_URL:https://gwy.dtiku.cn/pay/callback}"
