[web]
port = 18080
graceful = true

[web.middlewares]
static = { enable = true, uri = "/static", path = "static", precompressed = true }
# 因为和opentelemetry冲突所以写到代码里
logger = { enable = false, level = "${WEB_LOG_LEVEL:info}", override_filter = "${WEB_LOG_LEVEL_FILTER:info}" }

[sea-orm]
uri = "${DATABASE_URL:postgres://postgres:12345@localhost:5432/empty_tiku}"

[redis]
uri = "${REDIS_URL:redis://localhost}"

[opentelemetry]
enable = false

[site]
navbar_brand = "公考加油站"
site_title = "公考加油站"
show_ads = false
ads_script = ""
show_comments = true
show_visitors = true
show_solution = true
show_vendor = true
use_cdn_asset = false
cdn_assets = ""
alert_message_key = ""
global_alert_message = ""
analytics_script = ""
global_style = ""
global_head_files = ""
iconfont_js_url = "//at.alicdn.com/t/c/font_4936584_6w11ufwugtd.js"
block_user_agents = ""
seo_user_agents = ""
ip_blacklist = ""

[grpc-client]
embedding_url = "${EMBEDDING_GRPC_URL:http://localhost:18000}"
artalk_url = "${ARTALK_GRPC_URL:http://localhost:18090}"

[web-dav-client]
host = "${WEB_DAV_HOST:https://alist.dtiku.cn/dav}"
username = "${WEB_DAV_USERNAME:xxx}"
password = "${WEB_DAV_PASSWORD:xxx}"
