[web]
graceful = true

[web.middlewares]
static = { enable = true, uri = "/static", path = "static", precompressed = true }
# 因为和opentelemetry冲突所以写到代码里
logger = { enable = false, level = "${WEB_LOG_LEVEL:info}" }

[sea-orm]
uri = "${DATABASE_URL:postgres://postgres:12345@localhost:5432/postgres}"

[redis]
uri = "${REDIS_URL:redis://localhost}"
