###
POST https://alist.dtiku.cn/api/fs/get
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbG1vZnkiLCJwd2RfdHMiOjE3NDgxNDg2OTcsImV4cCI6MTc1ODgxNDA5NywibmJmIjoxNzU4NjQxMjk3LCJpYXQiOjE3NTg2NDEyOTd9._JARo87zNeSfAu_lQHVbFRaSxxsEMvVLztuZA_JkG40
Content-Type: application/json

{
  "path": "/assets/2025/8/26/2135257",
  "password": "",
  "page": 1,
  "per_page": 0,
  "refresh": false
}