[huggingface]
cache_dir = "${HF_HOME:../.hf-cache}"
text_model = "${TEXT_EMBEDDING_MODEL:MultilingualE5Base}"
img_model = "${IMAGE_EMBEDDING_MODEL:Resnet50}"

[grpc]
port = 18000

[logger]
# level = "debug"
pretty_backtrace = true
