[package]
name = "dtiku-base"
version = "0.0.0"
edition = "2021"

[dependencies]
spring = { workspace = true }
sea-orm = { workspace = true, features = ["sqlx-postgres"] }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
