//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use super::sea_orm_active_enums::SrcType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "assets_ref")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub src_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub src_type: SrcType,
    #[sea_orm(primary_key, auto_increment = false)]
    pub assets_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
