//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use crate::model::_entities::sea_orm_active_enums::FromType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "exam_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    pub name: String,
    pub prefix: String,
    pub pid: i16,
    pub from_ty: FromType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
