//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod assets;
pub mod assets_ref;
pub mod exam_category;
pub mod key_point;
pub mod label;
pub mod material;
pub mod paper;
pub mod paper_material;
pub mod paper_question;
pub mod question;
pub mod question_key_point;
pub mod question_key_point_stats;
pub mod question_material;
pub mod scraper_solution;
pub mod sea_orm_active_enums;
pub mod solution;
