//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod label;
pub mod material;
pub mod paper;
pub mod paper_material;
pub mod paper_question;
pub mod question;
pub mod question_material;
pub mod solution;
