//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "paper_question")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub paper_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub question_id: i32,
    pub sort: i16,
    #[sea_orm(column_type = "custom(\"ltree\")")]
    pub keypoint_path: String,
    #[sea_orm(column_type = "Float")]
    pub correct_ratio: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
