//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use crate::model::paper::PaperExtra;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "paper")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub year: i16,
    pub exam_id: i16,
    pub paper_type: i16,
    pub label_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra: PaperExtra,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
