//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::chapter_category::Entity as ChapterCategory;
pub use super::exam_category::Entity as ExamCategory;
pub use super::key_point::Entity as KeyPoint;
pub use super::label::Entity as Label;
pub use super::material::Entity as Material;
pub use super::paper::Entity as Paper;
pub use super::paper_material::Entity as PaperMaterial;
pub use super::paper_question::Entity as PaperQuestion;
pub use super::question::Entity as Question;
pub use super::question_key_point::Entity as QuestionKeyPoint;
pub use super::question_material::Entity as QuestionMaterial;
pub use super::solution::Entity as Solution;
