//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "question_key_point_stats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub key_point_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub year: i16,
    pub question_count: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
