//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "src_type")]
#[serde(rename_all = "snake_case")]
pub enum SrcType {
    #[sea_orm(string_value = "question")]
    Question,
    #[sea_orm(string_value = "material")]
    Material,
    #[sea_orm(string_value = "solution")]
    Solution,
}
