#:schema https://spring-rs.github.io/config-schema.json
[web]
port = 8000
graceful = true

[web.middlewares]
static = { enable = true, uri = "/", path = "frontend/dist" }

[logger]
# level = "debug"
pretty_backtrace = true

[sqlx]
uri = "${SRC_DATABASE_URL}"

[sea-orm]
uri = "${DATABASE_URL}"

[sea-orm-web]
one_indexed = true

[stream]
uri = "${REDIS_URL:redis://localhost}"

[redis]
uri = "${REDIS_URL:redis://localhost}"

[embedding]
url = "${EMBEDDING_URL:https://holmofy-dtiku-ai.hf.space}"

[openai]
endpoint = "${OPENAI_ENDPOINT:https://api.openai.com/v1}"
api_key = "${OPENROUTER_API_KEY}"

[opendal]
scheme = "webdav"
options = { endpoint = "${WEB_DAV_HOST:https://alist.dtiku.cn/dav}", username = "${WEB_DAV_USERNAME:xxx}", password = "${WEB_DAV_PASSWORD:xxx}" }
layers = ["Tracing"]

[site]
navbar_brand = "公考加油站"
site_title = "公考加油站"
show_ads = false
ads_script = ""
show_comments = true
show_visitors = true
show_solution = true
show_vendor = false
use_cdn_asset = false
cdn_assets = ""
alert_message_key = ""
global_alert_message = ""
analytics_script = ""
global_style = ""
global_head_files = ""
iconfont_js_url = "//at.alicdn.com/t/c/font_4936584_v34jg0cgwt.js"
block_ip_pv_threshold = 1000
block_user_agents = ""
seo_user_agents = ""
ip_blacklist = ""

[pay]
## https://openhome.alipay.com/develop/sandbox/app
test_pay_amount = ${TEST_PAY_AMOUNT:false}
wechat_pay_enable = false
alipay_enable = true
alipay_api_url = "${ALIPAY_API_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}"
alipay_app_id = "${ALIPAY_APP_ID:2021000149633962}"
alipay_root_cert_sn = "${ALIPAY_ROOT_CERT_SN}"
alipay_public_key = "${ALIPAY_PUBLIC_KEY}"
alipay_app_cert_sn = "${ALIPAY_APP_CERT_SN}"
alipay_app_private_key = "${ALIPAY_APP_PRIVATE_KEY}"
alipay_app_public_key = "${ALIPAY_APP_PUBLIC_KEY}"
alipay_callback_url = "${ALIPAY_CALLBACK_URL:https://p.dtiku.cn/pay/alipay/callback}"
