[web]
port = 8000
graceful = true

[web.middlewares]
static = { enable = true }

[sqlx]
uri = "postgres://postgres:12345@localhost:5432/dtiku"

[sea-orm]
uri = "postgres://postgres:12345@localhost:5432/postgres"

[stream]
uri = "redis://localhost"

[redis]
uri = "redis://localhost"
