[web]
port = 8000
graceful = true

[web.middlewares]
static = { enable = true }

[logger]
# level = "debug"
pretty_backtrace = true

[sqlx]
uri = "${SRC_DATABASE_URL}"

[sea-orm]
uri = "${DATABASE_URL}"

[stream]
uri = "${REDIS_URL:redis://localhost}"

[redis]
uri = "${REDIS_URL:redis://localhost}"

[huggingface]
cache_dir = "${HF_HOME../.hf-cache}"