[web]
port = 8000
graceful = true

[web.middlewares]
static = { enable = true }

[logger]
# level = "debug"
pretty_backtrace = true

[sqlx]
uri = "postgres://postgres:12345@localhost:5432/postgres?options=-c%20search_path%3Dpublic"

[sea-orm]
uri = "postgres://postgres:12345@localhost:5432/postgres?options=-c%20search_path%3Ddtiku"

[stream]
uri = "redis://localhost"

[redis]
uri = "redis://localhost"

[huggingface]
cache_dir = "../.hf-cache"