[web]
port = 8000
graceful = true

[web.middlewares]
static = { enable = true, uri = "/", path = "static" }

[logger]
# level = "debug"
pretty_backtrace = true

[sqlx]
uri = "${SRC_DATABASE_URL}"

[sea-orm]
uri = "${DATABASE_URL}"

[stream]
uri = "${REDIS_URL:redis://localhost}"

[redis]
uri = "${REDIS_URL:redis://localhost}"

[embedding]
url = "${EMBEDDING_URL:http://localhost:9090}"
