[package]
name = "dtiku-web"
version = "0.0.1"
edition = "2021"
publish = ["crates-io"]

[[bin]]
name = "web"
path = "src/main.rs"

[dependencies]
spring = { workspace = true }
spring-web = { workspace = true }
spring-sea-orm = { workspace = true, features = ["postgres"] }
spring-redis = { workspace = true }
tokio = { workspace = true, features = ["full"] }
dtiku-paper = { path = "../dtiku-paper", version = "0.0.1" }
askama = { workspace = true }
anyhow = { workspace = true }