name: Publish Docker Image CI use Dockerfile

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: "指定dockerfile"
        default: "postgres"

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to build dtiku-artalk image.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: .buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Dockerhub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME}}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWD }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: docker/${{ github.event.inputs.dockerfile }}.Dockerfile
          push: true
          tags: holmofy/${{ github.event.inputs.dockerfile }}:latest
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache-new,mode=max
      - name: Move cache back
        run: |
          rm -rf .buildx-cache
          mv .buildx-cache-new .buildx-cache
