//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use crate::model::enums::ScheduleTaskType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "schedule_task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: i32,
    pub ty: ScheduleTaskType,
    pub active: bool,
    #[sea_orm(column_type = "JsonBinary")]
    pub context: Json,
    pub run_count: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub instance_ids: Json,
    pub created: DateTime,
    pub modified: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
